### ISSUE TITLE
Some way to stay on the tracing object

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.DeveloperTools.Unity#5]
## Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/22952143/106992611-ce20e000-67b3-11eb-8c81-b7da31a3de92.png)

For example, I want to know and inspect what call into GameController's methods.
I selected Game Controller, rebuild the cache and select the GameController component,
the list of button shows all the calling site.
I click one of them and it 'shows' me the calling target. (On Ship Destroyed in this example)

![image](https://user-images.githubusercontent.com/22952143/106992862-65863300-67b4-11eb-9d5f-f6c245a455b7.png)
However, when I then 'click and select' to inspect the calling target, the Tracer is also cleared.

Often we have to inspect several of them to find the correct target, meaning we have to click on GameController, rebuild, select a calling target, inspect, select GameController again multiple times.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/22952143/106993368-84d19000-67b5-11eb-9548-b552c40dd6ef.png)
I would like a 'lock' button just like the one on the Inspector to let the Tracer stay on the previous selected object.

## Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/22952143/106993767-61f3ab80-67b6-11eb-9100-9cf2426104a7.png)
a target field that stays.

**Comment by thestonefox** [comment]
I think the target field is probably feasible.

**Comment by thestonefox** [comment]
Why not both:

![image](https://user-images.githubusercontent.com/1029673/157732757-cb264ad9-ba76-4ffe-900d-c8fda7a4b7af.png)

History list of all items previously used as the target.

And the ability to lock it:

![image](https://user-images.githubusercontent.com/1029673/157732826-86625265-e7b8-4fc7-b63d-f71569fc0d35.png)


PR with solution: https://github.com/ExtendRealityLtd/Tilia.DeveloperTools.Unity/pull/29
